version: '3.8'

services:
  # 1. O Banco de Dados PostgreSQL.
  nexus-db:
    image: postgres:15
    container_name: nexus_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-senha_super_forte}
      POSTGRES_DB: ${DB_NAME:-nexus_db}
    ports:
      - "5432:5432"
    volumes:
      - nexus_pgdata:/var/lib/postgresql/data

  # 2. O Backend (Python / FastAPI)
  nexus-api:
    build: .
    container_name: nexus_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - nexus-db
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=AKIA4VPN43D6KCHKRYM5
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-east-1
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # 3. O Frontend (React / Nginx)
  nexus-web:
    build: ./nexus-frontend
    container_name: nexus_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - nexus-api

volumes:
  nexus_pgdata: