"""Atualizando_schema_completo

Revision ID: 6adb9c0e79d4
Revises: c5d274ceec67
Create Date: 2026-04-03 10:39:54.253231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adb9c0e79d4'
down_revision: Union[str, Sequence[str], None] = 'c5d274ceec67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_clientes', sa.Column('bloqueado', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_clientes', 'bloqueado')
    # ### end Alembic commands ###
