"""Add primeiro_acesso

Revision ID: 6fbfc2218e1e
Revises: 6adb9c0e79d4
Create Date: 2026-04-03 10:52:05.749245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbfc2218e1e'
down_revision: Union[str, Sequence[str], None] = '6adb9c0e79d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('primeiro_acesso', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'primeiro_acesso')
    # ### end Alembic commands ###
