"""Criando fundacao do Nexus

Revision ID: c5d274ceec67
Revises: 
Create Date: 2026-04-02 23:48:56.607795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d274ceec67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_ajustes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ciclo_sop', sa.String(length=10), nullable=False),
    sa.Column('data_ajuste', sa.DateTime(), nullable=True),
    sa.Column('origem_ajuste', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('razaosocial_afetada', sa.String(length=255), nullable=False),
    sa.Column('mes_projetado', sa.Date(), nullable=False),
    sa.Column('vol_novo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_ajustes_ciclo_sop'), 'auditoria_ajustes', ['ciclo_sop'], unique=False)
    op.create_table('controle_ciclos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ciclo_sop', sa.String(length=10), nullable=False),
    sa.Column('origem', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ciclo_sop', 'origem', name='uix_ciclo_origem')
    )
    op.create_index(op.f('ix_controle_ciclos_ciclo_sop'), 'controle_ciclos', ['ciclo_sop'], unique=False)
    op.create_table('dim_clientes',
    sa.Column('cgc', sa.String(length=50), nullable=False),
    sa.Column('cod_cliente', sa.String(length=50), nullable=False),
    sa.Column('loja', sa.String(length=50), nullable=False),
    sa.Column('razaosocial', sa.String(length=255), nullable=False),
    sa.Column('regional', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cgc')
    )
    op.create_index(op.f('ix_dim_clientes_cgc'), 'dim_clientes', ['cgc'], unique=False)
    op.create_index(op.f('ix_dim_clientes_razaosocial'), 'dim_clientes', ['razaosocial'], unique=False)
    op.create_table('dim_produtos',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('bu', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('segmento', sa.String(length=100), nullable=True),
    sa.Column('curva', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_dim_produtos_sku'), 'dim_produtos', ['sku'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('funcao', sa.String(length=50), nullable=False),
    sa.Column('nome_vendedor', sa.String(length=100), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('fato_acuracia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ciclo_avaliado', sa.String(length=10), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('vendedor_nome', sa.String(length=100), nullable=False),
    sa.Column('vol_realizado', sa.Integer(), nullable=True),
    sa.Column('acuracia_ia', sa.Float(), nullable=True),
    sa.Column('acuracia_topdown', sa.Float(), nullable=True),
    sa.Column('acuracia_bottomup', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['dim_produtos.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fato_ibp_granular',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ciclo_sop', sa.String(length=10), nullable=False),
    sa.Column('mes_projetado', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('cgc', sa.String(length=50), nullable=False),
    sa.Column('vendedor_nome', sa.String(length=100), nullable=True),
    sa.Column('vol_ia', sa.Integer(), nullable=True),
    sa.Column('vol_topdown', sa.Integer(), nullable=True),
    sa.Column('vol_bottomup', sa.Integer(), nullable=True),
    sa.Column('pmv_aplicado', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cgc'], ['dim_clientes.cgc'], ),
    sa.ForeignKeyConstraint(['sku'], ['dim_produtos.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ciclo_sop', 'mes_projetado', 'sku', 'cgc', name='uix_forecast_atomico')
    )
    op.create_index(op.f('ix_fato_ibp_granular_ciclo_sop'), 'fato_ibp_granular', ['ciclo_sop'], unique=False)
    op.create_index(op.f('ix_fato_ibp_granular_mes_projetado'), 'fato_ibp_granular', ['mes_projetado'], unique=False)
    op.create_index(op.f('ix_fato_ibp_granular_vendedor_nome'), 'fato_ibp_granular', ['vendedor_nome'], unique=False)
    op.create_table('fato_vendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('cgc', sa.String(length=50), nullable=False),
    sa.Column('vendedor_nome', sa.String(length=100), nullable=True),
    sa.Column('qt_pedido', sa.Float(), nullable=True),
    sa.Column('vl_pedido', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cgc'], ['dim_clientes.cgc'], ),
    sa.ForeignKeyConstraint(['sku'], ['dim_produtos.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fato_vendas_data_pedido'), 'fato_vendas', ['data_pedido'], unique=False)
    op.create_index(op.f('ix_fato_vendas_vendedor_nome'), 'fato_vendas', ['vendedor_nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fato_vendas_vendedor_nome'), table_name='fato_vendas')
    op.drop_index(op.f('ix_fato_vendas_data_pedido'), table_name='fato_vendas')
    op.drop_table('fato_vendas')
    op.drop_index(op.f('ix_fato_ibp_granular_vendedor_nome'), table_name='fato_ibp_granular')
    op.drop_index(op.f('ix_fato_ibp_granular_mes_projetado'), table_name='fato_ibp_granular')
    op.drop_index(op.f('ix_fato_ibp_granular_ciclo_sop'), table_name='fato_ibp_granular')
    op.drop_table('fato_ibp_granular')
    op.drop_table('fato_acuracia')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_dim_produtos_sku'), table_name='dim_produtos')
    op.drop_table('dim_produtos')
    op.drop_index(op.f('ix_dim_clientes_razaosocial'), table_name='dim_clientes')
    op.drop_index(op.f('ix_dim_clientes_cgc'), table_name='dim_clientes')
    op.drop_table('dim_clientes')
    op.drop_index(op.f('ix_controle_ciclos_ciclo_sop'), table_name='controle_ciclos')
    op.drop_table('controle_ciclos')
    op.drop_index(op.f('ix_auditoria_ajustes_ciclo_sop'), table_name='auditoria_ajustes')
    op.drop_table('auditoria_ajustes')
    # ### end Alembic commands ###
