server {
    listen 80;
    
    # Onde os arquivos do React vão ficar
    root /usr/share/nginx/html;
    index index.html;

    # Regra de ouro para o React Router funcionar (não dar erro 404 ao dar F5)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de ficheiros estáticos para o sistema carregar super rápido
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}